apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: m5-blue-service
  description: My Spring Boot microservice
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: my-team
